### ISSUE TITLE
[Improvement] Readme lacks a beautiful GIF of tool's TUI

### ISSUE THREAD

**Issue by fadeevab** [cylewitruk/stackify#1]
:) You could add a GIF how your tool works like this

![image](https://private-user-images.githubusercontent.com/35576205/319738836-ab2f04c1-770e-4dac-bb75-6fe82c4943a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MjU1ODgsIm5iZiI6MTcxMzQyNTI4OCwicGF0aCI6Ii8zNTU3NjIwNS8zMTk3Mzg4MzYtYWIyZjA0YzEtNzcwZS00ZGFjLWJiNzUtNmZlODJjNDk0M2ExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDA3MjgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2YzNkZmU4NThiNmVjMWQ4ZTkyZTM5MzJhMTkwOThhODViZjIxOTlhMTQ3NGE2ZmY1MmMyYzFhYWEwNmY3M2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PhaNrPSd-HpH3n1wRhzuNvGaEWceYvvSpAU8_uzKsiM)

**Comment by cylewitruk** [comment]
Hehe I know it's lacking -- right now it's just a `clap` dump so it wasn't empty, have been meaning to write a "pretty" readme and move the clap stuff to another page :smile:

**Comment by cylewitruk** [comment]
What do you use to create your gifs btw @fadeevab ?

**Comment by fadeevab** [comment]
@cylewitruk I use https://www.screentogif.com/, but it's for Windows. I use Windows + WSL2 (subsystem for Linux).

**Comment by cylewitruk** [comment]
> @cylewitruk I use [screentogif.com](https://www.screentogif.com/), but it's for Windows. I use Windows + WSL2 (subsystem for Linux).

Aha, I'm on linux, but I did find a nice tool [peek](https://github.com/phw/peek) which looks promising :)

**Comment by cylewitruk** [comment]
@fadeevab finally got around to starting work on the readme 😁 Will put a little cliclack shoutout in there somewhere as well 😉
